name = "attendance-management-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[env.production]
name = "attendance-management-frontend"

[env.staging]
name = "attendance-management-frontend-staging"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
