services:
  - type: web
    name: attendance-backend
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-postgres
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
    buildCommand: docker build -t attendance-backend .
    startCommand: ./start.sh

databases:
  - name: attendance-postgres
    databaseName: attendance_db
    user: attendance_user
    plan: starter
    region: oregon
