services:
  - type: web
    name: attendance-backend
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    buildCommand: docker build -t attendance-backend .
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-postgres
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      - key: FIRST_SUPERUSER_PASSWORD
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_HOST
        value: "https://your-frontend-domain.com"
      - key: BACKEND_CORS_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:5173"

databases:
  - name: attendance-postgres
    databaseName: attendance_db
    user: attendance_user
    plan: starter
    region: oregon
