name = "lamhatrack"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "frontend/dist"

# Environment configurations
[env.production]
name = "lamhatrack"
