name = "attendance-management-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[site]
bucket = "frontend/dist"

# Environment configurations
[env.production]
name = "attendance-management-frontend"

[env.staging]
name = "attendance-management-frontend-staging"
