// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DepartmentsReadDepartmentsData, DepartmentsReadDepartmentsResponse, DepartmentsCreateDepartmentData, DepartmentsCreateDepartmentResponse, DepartmentsReadDepartmentData, DepartmentsReadDepartmentResponse, DepartmentsUpdateDepartmentData, DepartmentsUpdateDepartmentResponse, DepartmentsDeleteDepartmentData, DepartmentsDeleteDepartmentResponse, EmployeesReadEmployeesData, EmployeesReadEmployeesResponse, EmployeesCreateEmployeeData, EmployeesCreateEmployeeResponse, EmployeesReadEmployeeData, EmployeesReadEmployeeResponse, EmployeesUpdateEmployeeData, EmployeesUpdateEmployeeResponse, EmployeesDeleteEmployeeData, EmployeesDeleteEmployeeResponse, EmployeesReadEmployeeByEmployeeIdData, EmployeesReadEmployeeByEmployeeIdResponse, EmployeesReadEmployeeByCnicData, EmployeesReadEmployeeByCnicResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DepartmentsService {
    /**
     * Read Departments
     * Retrieve departments.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns DepartmentPublic Successful Response
     * @throws ApiError
     */
    public static readDepartments(data: DepartmentsReadDepartmentsData = {}): CancelablePromise<DepartmentsReadDepartmentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/departments/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Department
     * Create new department.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DepartmentPublic Successful Response
     * @throws ApiError
     */
    public static createDepartment(data: DepartmentsCreateDepartmentData): CancelablePromise<DepartmentsCreateDepartmentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/departments/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Department
     * Get department by ID.
     * @param data The data for the request.
     * @param data.departmentId
     * @returns DepartmentPublic Successful Response
     * @throws ApiError
     */
    public static readDepartment(data: DepartmentsReadDepartmentData): CancelablePromise<DepartmentsReadDepartmentResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/departments/{department_id}',
            path: {
                department_id: data.departmentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Department
     * Update department.
     * @param data The data for the request.
     * @param data.departmentId
     * @param data.requestBody
     * @returns DepartmentPublic Successful Response
     * @throws ApiError
     */
    public static updateDepartment(data: DepartmentsUpdateDepartmentData): CancelablePromise<DepartmentsUpdateDepartmentResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/departments/{department_id}',
            path: {
                department_id: data.departmentId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Department
     * Delete department.
     * @param data The data for the request.
     * @param data.departmentId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteDepartment(data: DepartmentsDeleteDepartmentData): CancelablePromise<DepartmentsDeleteDepartmentResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/departments/{department_id}',
            path: {
                department_id: data.departmentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class EmployeesService {
    /**
     * Read Employees
     * Retrieve employees.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.departmentId Filter by department ID
     * @returns EmployeesPublic Successful Response
     * @throws ApiError
     */
    public static readEmployees(data: EmployeesReadEmployeesData = {}): CancelablePromise<EmployeesReadEmployeesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/employees/',
            query: {
                skip: data.skip,
                limit: data.limit,
                department_id: data.departmentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Employee
     * Create new employee.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns EmployeePublic Successful Response
     * @throws ApiError
     */
    public static createEmployee(data: EmployeesCreateEmployeeData): CancelablePromise<EmployeesCreateEmployeeResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/employees/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Employee
     * Get employee by ID.
     * @param data The data for the request.
     * @param data.employeeId
     * @returns EmployeePublic Successful Response
     * @throws ApiError
     */
    public static readEmployee(data: EmployeesReadEmployeeData): CancelablePromise<EmployeesReadEmployeeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/employees/{employee_id}',
            path: {
                employee_id: data.employeeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Employee
     * Update employee.
     * @param data The data for the request.
     * @param data.employeeId
     * @param data.requestBody
     * @returns EmployeePublic Successful Response
     * @throws ApiError
     */
    public static updateEmployee(data: EmployeesUpdateEmployeeData): CancelablePromise<EmployeesUpdateEmployeeResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/employees/{employee_id}',
            path: {
                employee_id: data.employeeId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Employee
     * Delete employee.
     * @param data The data for the request.
     * @param data.employeeId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteEmployee(data: EmployeesDeleteEmployeeData): CancelablePromise<EmployeesDeleteEmployeeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/employees/{employee_id}',
            path: {
                employee_id: data.employeeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Employee By Employee Id
     * Get employee by employee ID (company ID).
     * @param data The data for the request.
     * @param data.employeeId
     * @returns EmployeePublic Successful Response
     * @throws ApiError
     */
    public static readEmployeeByEmployeeId(data: EmployeesReadEmployeeByEmployeeIdData): CancelablePromise<EmployeesReadEmployeeByEmployeeIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/employees/by-employee-id/{employee_id}',
            path: {
                employee_id: data.employeeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Employee By Cnic
     * Get employee by CNIC.
     * @param data The data for the request.
     * @param data.cnic
     * @returns EmployeePublic Successful Response
     * @throws ApiError
     */
    public static readEmployeeByCnic(data: EmployeesReadEmployeeByCnicData): CancelablePromise<EmployeesReadEmployeeByCnicResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/employees/by-cnic/{cnic}',
            path: {
                cnic: data.cnic
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
}