// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DepartmentCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

export type DepartmentPublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type DepartmentUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type EmployeeCreate = {
    employee_id: string;
    cnic: string;
    first_name: string;
    last_name: string;
    phone: string;
    address?: (string | null);
    date_of_birth?: (string | null);
    hire_date: string;
    salary?: (number | null);
    is_active?: boolean;
    emergency_contact_name?: (string | null);
    emergency_contact_phone?: (string | null);
    department_id: string;
    user_id?: (string | null);
};

export type EmployeePublic = {
    employee_id: string;
    cnic: string;
    first_name: string;
    last_name: string;
    phone: string;
    address?: (string | null);
    date_of_birth?: (string | null);
    hire_date: string;
    salary?: (number | null);
    is_active?: boolean;
    emergency_contact_name?: (string | null);
    emergency_contact_phone?: (string | null);
    id: string;
    department_id: string;
    user_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type EmployeesPublic = {
    data: Array<EmployeePublic>;
    count: number;
};

export type EmployeeUpdate = {
    employee_id?: (string | null);
    cnic?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    date_of_birth?: (string | null);
    hire_date?: (string | null);
    salary?: (number | null);
    is_active?: (boolean | null);
    emergency_contact_name?: (string | null);
    emergency_contact_phone?: (string | null);
    department_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DepartmentsReadDepartmentsData = {
    limit?: number;
    skip?: number;
};

export type DepartmentsReadDepartmentsResponse = (Array<DepartmentPublic>);

export type DepartmentsCreateDepartmentData = {
    requestBody: DepartmentCreate;
};

export type DepartmentsCreateDepartmentResponse = (DepartmentPublic);

export type DepartmentsReadDepartmentData = {
    departmentId: string;
};

export type DepartmentsReadDepartmentResponse = (DepartmentPublic);

export type DepartmentsUpdateDepartmentData = {
    departmentId: string;
    requestBody: DepartmentUpdate;
};

export type DepartmentsUpdateDepartmentResponse = (DepartmentPublic);

export type DepartmentsDeleteDepartmentData = {
    departmentId: string;
};

export type DepartmentsDeleteDepartmentResponse = (unknown);

export type EmployeesReadEmployeesData = {
    /**
     * Filter by department ID
     */
    departmentId?: (string | null);
    limit?: number;
    skip?: number;
};

export type EmployeesReadEmployeesResponse = (EmployeesPublic);

export type EmployeesCreateEmployeeData = {
    requestBody: EmployeeCreate;
};

export type EmployeesCreateEmployeeResponse = (EmployeePublic);

export type EmployeesReadEmployeeData = {
    employeeId: string;
};

export type EmployeesReadEmployeeResponse = (EmployeePublic);

export type EmployeesUpdateEmployeeData = {
    employeeId: string;
    requestBody: EmployeeUpdate;
};

export type EmployeesUpdateEmployeeResponse = (EmployeePublic);

export type EmployeesDeleteEmployeeData = {
    employeeId: string;
};

export type EmployeesDeleteEmployeeResponse = (unknown);

export type EmployeesReadEmployeeByEmployeeIdData = {
    employeeId: string;
};

export type EmployeesReadEmployeeByEmployeeIdResponse = (EmployeePublic);

export type EmployeesReadEmployeeByCnicData = {
    cnic: string;
};

export type EmployeesReadEmployeeByCnicResponse = (EmployeePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);