"""add_fingerprint_storage

Revision ID: 49a3ae34e5b4
Revises: 004_add_zkteco_integration
Create Date: 2025-08-30 21:47:57.768671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '49a3ae34e5b4'
down_revision = '004_add_zkteco_integration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_attendance_type', table_name='attendance')
    op.drop_index('ix_attendance_check_in_time', table_name='attendance')
    op.drop_index('ix_attendance_employee_id', table_name='attendance')
    op.drop_index('ix_attendance_status', table_name='attendance')
    op.drop_index('ix_attendance_zkteco_device_id', table_name='attendance')
    op.drop_constraint('attendance_employee_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'employee', ['employee_id'], ['id'])
    op.drop_index('ix_devicesynclog_created_at', table_name='devicesynclog')
    op.drop_index('ix_devicesynclog_device_id', table_name='devicesynclog')
    op.drop_index('ix_devicesynclog_sync_status', table_name='devicesynclog')
    op.drop_index('ix_devicesynclog_sync_type', table_name='devicesynclog')
    op.drop_constraint('fk_devicesynclog_device_id', 'devicesynclog', type_='foreignkey')
    op.drop_constraint('employee_cnic_key', 'employee', type_='unique')
    op.drop_constraint('employee_employee_id_key', 'employee', type_='unique')
    op.drop_index('ix_employee_department_id', table_name='employee')
    op.drop_index('ix_employee_user_id', table_name='employee')
    op.drop_index('ix_employee_cnic', table_name='employee')
    op.create_index(op.f('ix_employee_cnic'), 'employee', ['cnic'], unique=True)
    op.drop_index('ix_employee_employee_id', table_name='employee')
    op.create_index(op.f('ix_employee_employee_id'), 'employee', ['employee_id'], unique=True)
    op.drop_constraint('employee_department_id_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_user_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'user', ['user_id'], ['id'])
    op.alter_column('fingerprint', 'fingerprint_data',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000000),
               existing_nullable=False)
    op.drop_index('ix_fingerprint_created_at', table_name='fingerprint')
    op.drop_index('ix_fingerprint_employee_id', table_name='fingerprint')
    op.drop_index('ix_fingerprint_fingerprint_type', table_name='fingerprint')
    op.drop_index('ix_fingerprint_is_active', table_name='fingerprint')
    op.drop_constraint('uq_fingerprint_employee_type_position', 'fingerprint', type_='unique')
    op.drop_constraint('fingerprint_employee_id_fkey', 'fingerprint', type_='foreignkey')
    op.create_foreign_key(None, 'fingerprint', 'employee', ['employee_id'], ['id'])
    op.drop_index('ix_zktecodevice_device_id', table_name='zktecodevice')
    op.drop_index('ix_zktecodevice_device_ip', table_name='zktecodevice')
    op.drop_index('ix_zktecodevice_is_active', table_name='zktecodevice')
    op.create_unique_constraint(None, 'zktecodevice', ['device_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zktecodevice', type_='unique')
    op.create_index('ix_zktecodevice_is_active', 'zktecodevice', ['is_active'], unique=False)
    op.create_index('ix_zktecodevice_device_ip', 'zktecodevice', ['device_ip'], unique=False)
    op.create_index('ix_zktecodevice_device_id', 'zktecodevice', ['device_id'], unique=True)
    op.drop_constraint(None, 'fingerprint', type_='foreignkey')
    op.create_foreign_key('fingerprint_employee_id_fkey', 'fingerprint', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_fingerprint_employee_type_position', 'fingerprint', ['employee_id', 'fingerprint_type', 'fingerprint_position'])
    op.create_index('ix_fingerprint_is_active', 'fingerprint', ['is_active'], unique=False)
    op.create_index('ix_fingerprint_fingerprint_type', 'fingerprint', ['fingerprint_type'], unique=False)
    op.create_index('ix_fingerprint_employee_id', 'fingerprint', ['employee_id'], unique=False)
    op.create_index('ix_fingerprint_created_at', 'fingerprint', ['created_at'], unique=False)
    op.alter_column('fingerprint', 'fingerprint_data',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_user_id_fkey', 'employee', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('employee_department_id_fkey', 'employee', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employee_employee_id'), table_name='employee')
    op.create_index('ix_employee_employee_id', 'employee', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_employee_cnic'), table_name='employee')
    op.create_index('ix_employee_cnic', 'employee', ['cnic'], unique=False)
    op.create_index('ix_employee_user_id', 'employee', ['user_id'], unique=False)
    op.create_index('ix_employee_department_id', 'employee', ['department_id'], unique=False)
    op.create_unique_constraint('employee_employee_id_key', 'employee', ['employee_id'])
    op.create_unique_constraint('employee_cnic_key', 'employee', ['cnic'])
    op.create_foreign_key('fk_devicesynclog_device_id', 'devicesynclog', 'zktecodevice', ['device_id'], ['id'])
    op.create_index('ix_devicesynclog_sync_type', 'devicesynclog', ['sync_type'], unique=False)
    op.create_index('ix_devicesynclog_sync_status', 'devicesynclog', ['sync_status'], unique=False)
    op.create_index('ix_devicesynclog_device_id', 'devicesynclog', ['device_id'], unique=False)
    op.create_index('ix_devicesynclog_created_at', 'devicesynclog', ['created_at'], unique=False)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_employee_id_fkey', 'attendance', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_attendance_zkteco_device_id', 'attendance', ['zkteco_device_id'], unique=False)
    op.create_index('ix_attendance_status', 'attendance', ['status'], unique=False)
    op.create_index('ix_attendance_employee_id', 'attendance', ['employee_id'], unique=False)
    op.create_index('ix_attendance_check_in_time', 'attendance', ['check_in_time'], unique=False)
    op.create_index('ix_attendance_attendance_type', 'attendance', ['attendance_type'], unique=False)
    # ### end Alembic commands ###
